config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update'
  get 'tasks/:id', to: 'tasks#show', as: :task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
   end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
  <%= form_for(@task) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, :class => 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label :completed %>
      <%= f.check_box :completed, :class => 'form-control' %>
      </div>
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to "back to list", tasks_path, :class => " btn btn-primary" %>
    </div>
  <% end %>

  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center m-3">
    <h1>MY TASKS</h1>
  </div>
  <div class= "d-flex justify-content-center m-3 p-5 ">
    <ul>
      <% @tasks.each do |task|  %>
      <div class="form-check ">
        <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
        <label class="form-check-label" for="defaultCheck1">
        <%= link_to task.title, task_path(task) %></label>
      </div>
    <% end %>
    </ul>
  </div>
  <div class="text-center">
    <%= link_to "add a new task", tasks_new_path,  :class => " btn btn-primary"  %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="d-flex justify-content-center">
  <%= form_for(@task) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, :class => 'form-control' %>
      </div>
      <div class="form-group">
      <%= f.label :completed %>
      <%= f.check_box :completed, :class => 'form-control' %>
      </div>
      <%= f.submit :class => 'btn btn-primary' %>
      <%= link_to "back to list", tasks_path, :class => " btn btn-primary"  %>
    </div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="text-center m-5">

    <h3><%= @task.title %></h3>
    <p><%= @task.details %></p>
    <p>Completion: <%= @task.completed == true ? "✔️" : "❌" %></p>
    <%= link_to "back to list", tasks_path, :class => "btn btn-primary" %>
    <%= link_to "edit", edit_path, :class => "btn btn-primary"  %>
    <%= link_to "Delete",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" }, :class => "btn btn-primary" %>
  </div>
</div>